const elements = [
  {
    tag: "a",
    title: "<a>: The Anchor element",
    description: "The <a> HTML element (or anchor element), with its href attribute, creates a hyperlink to web pages, files, email addresses, locations in the same page, or anything else a URL can address."
  },
  {
    tag: "abbr",
    title: "<abbr>: The Abbreviation element",
    description: "The <abbr> HTML element represents an abbreviation or acronym; the optional title attribute can provide an expansion or description for the abbreviation. If present, title must contain this full description and nothing else."
  },
  {
    tag: "address",
    title: "<address>: The Contact Address element",
    description: "The <address> HTML element indicates that the enclosed HTML provides contact information for a person or people, or for an organization."
  },
  {
    tag: "area",
    title: "<area>: The Image Map Area element",
    description: "The <area> HTML element defines an area inside an image map that has predefined clickable areas. An image map allows geometric areas on an image to be associated with hypertext link."
  },
  {
    tag: "article",
    title: "<article>: The Article Contents element",
    description: "The <article> HTML element represents a self-contained composition in a document, page, application, or site, which is intended to be independently distributable or reusable (e.g., in syndication). Examples include: a forum post, a magazine or newspaper article, or a blog entry, a product card, a user-submitted comment, an interactive widget or gadget, or any other independent item of content."
  },
  {
    tag: "aside",
    title: "<aside>: The Aside element",
    description: "The <aside> HTML element represents a portion of a document whose content is only indirectly related to the document's main content. Asides are frequently presented as sidebars or call-out boxes."
  },
  {
    tag: "audio",
    title: "<audio>: The Embed Audio element",
    description: "The <audio> HTML element is used to embed sound content in documents. It may contain one or more audio sources, represented using the src attribute or the <source> element: the browser will choose the most suitable one. It can also be the destination for streamed media, using a MediaStream."
  },
  {
    tag: "b",
    title: "<b>: The Bring Attention To element",
    description: "The <b> HTML element is used to draw the reader's attention to the element's contents, which are not otherwise granted special importance. This was formerly known as the Boldface element, and most browsers still draw the text in boldface. However, you should not use <b> for styling text; instead, you should use the CSS font-weight property to create boldface text, or the <strong> element to indicate that text is of special importance."
  },
  {
    tag: "base",
    title: "<base>: The Document Base URL element",
    description: "The <base> HTML element specifies the base URL to use for all relative URLs in a document. There can be only one <base> element in a document."
  },
  {
    tag: "bdi",
    title: "<bdi>: The Bidirectional Isolate element",
    description: "The <bdi> HTML element tells the browser's bidirectional algorithm to treat the text it contains in isolation from its surrounding text. It's particularly useful when a website dynamically inserts some text and doesn't know the directionality of the text being inserted."
  }
];

const attributes = [
  {
    tag: "accept",
    isGlobal: false,
    elements: [
      "<form>",
      "<input>"
    ],
    description: "List of types the server accepts, typically a file type."
  },
  {
    tag: "accept-charset",
    isGlobal: false,
    elements: [
      "<form>"
    ],
    description: "List of supported charsets."
  },
  {
    tag: "accesskey",
    isGlobal: true,
    elements: [
      ""
    ],
    description: "The accesskey global attribute provides a hint for generating a keyboard shortcut for the current element. The attribute value must consist of a single printable character (which includes accented and other characters that can be generated by the keyboard)."
  },
  {
    tag: "action",
    isGlobal: false,
    elements: [
      "<form>"
    ],
    description: "The URI of a program that processes the information submitted via the form."
  },
  {
    tag: "align",
    isGlobal: false,
    elements: [
      "<applet>",
      "<caption>",
      "<col>",
      "<colgroup>",
      "<hr>",
      "<iframe>",
      "<img>",
      "<table>",
      "<tbody>",
      "<td>",
      "<tfoot>",
      "<th>",
      "<thead>",
      "<tr>"
    ],
    description: "Specifies the horizontal alignment of the element."
  },
  {
    tag: "allow",
    isGlobal: false,
    elements: [
      "<iframe>"
    ],
    description: "Specifies a feature-policy for the iframe."
  },
  {
    tag: "alt",
    isGlobal: false,
    elements: [
      "<applet>",
      "<area>",
      "<img>",
      "<input>"
    ],
    description: "Alternative text in case an image can't be displayed."
  },
  {
    tag: "async",
    isGlobal: false,
    elements: [
      "<script>"
    ],
    description: "Executes the script asynchronously."
  },
  {
    tag: "autocapitalize",
    isGlobal: true,
    elements: [
      ""
    ],
    description: "The autocapitalize global attribute is an enumerated attribute that controls whether and how text input is automatically capitalized as it is entered/edited by the user."
  },
  {
    tag: "autocomplete",
    isGlobal: false,
    elements: [
      "<form>",
      "<input>",
      "<select>",
      "<textarea>"
    ],
    description: "Indicates whether controls in this form can by default have their values automatically completed by the browser."
  },
  {
    tag: "autofocus",
    isGlobal: false,
    elements: [
      "<button>",
      "<input>",
      "<keygen>",
      "<select>",
      "<textarea>"
    ],
    description: "The element should be automatically focused after the page loaded."
  },
  {
    tag: "autofocus",
    isGlobal: true,
    elements: [
      ""
    ],
    description: "The autofocus global attribute is a Boolean attribute indicating that an element should be focused on page load, or when the <dialog> that it is part of is displayed."
  },
  {
    tag: "autoplay",
    isGlobal: false,
    elements: [
      "<audio>",
      "<video>"
    ],
    description: "The audio or video should play as soon as possible."
  },
  {
    tag: "background",
    isGlobal: false,
    elements: [
      "<body>",
      "<table>",
      "<td>",
      "<th>"
    ],
    description: "Specifies the URL of an image file."
  },
  {
    tag: "bgcolor",
    isGlobal: false,
    elements: [
      "<body>",
      "<col>",
      "<colgroup>",
      "<marquee>",
      "<table>",
      "<tbody>",
      "<tfoot>",
      "<td>",
      "<th>",
      "<tr>"
    ],
    description: "Background color of the element."
  },
  {
    tag: "border",
    isGlobal: false,
    elements: [
      "<img>",
      "<object>",
      "<table>"
    ],
    description: "The border width."
  },
  {
    tag: "buffered",
    isGlobal: false,
    elements: [
      "<audio>",
      "<video>"
    ],
    description: "Contains the time range of already buffered media."
  },
  {
    tag: "capture",
    isGlobal: false,
    elements: [
      "<input>"
    ],
    description: "From the Media Capture specification, specifies a new file can be captured."
  },
  {
    tag: "challenge",
    isGlobal: false,
    elements: [
      "<keygen>"
    ],
    description: "A challenge string that is submitted along with the public key."
  },
  {
    tag: "charset",
    isGlobal: false,
    elements: [
      "<meta>",
      "<script>"
    ],
    description: "Declares the character encoding of the page or script."
  },
  {
    tag: "checked",
    isGlobal: false,
    elements: [
      "<command>",
      "<input>"
    ],
    description: "Indicates whether the element should be checked on page load."
  },
  {
    tag: "cite",
    isGlobal: false,
    elements: [
      "<blockquote>",
      "<del>",
      "<ins>",
      "<q>"
    ],
    description: "Contains a URI which points to the source of the quote or change."
  }
]

export const htmlData = {
  icon: "logo-html5",
  title: "html",
  subItems: [
    {
      title: "elements",
      content: elements
    },
    {
      title: "attributes",
      content: attributes
    }
  ]
};